// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    Headers: typeof import('./src/components/Headers.vue')['default']
    Home: typeof import('./src/views/Home/Home.vue')['default']
    Index: typeof import('./src/views/Index/Index.vue')['default']
    IndexColumn: typeof import('./src/views/Index/components/IndexColumn.vue')['default']
    IndexCount: typeof import('./src/views/Index/components/IndexColumn.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Tool: typeof import('./src/views/tool/Tool.vue')['default']
    VmdContent: typeof import('./src/views/editor/VmdContent.vue')['default']
  }
}

export { }
